#!/bin/sh

bindir="$(dirname "$0")"

ZMB="${bindir}/zmb"
JQ="$(which jq)"

error () {
    status="$1"
    message="$2"
    echo "error: ${message}" >&2
    exit "${status}"
}

zmb () {
    json="$("${ZMB}" "$@" 2>&1)" || error 1 "method $1: ${json}"
    echo "${json}" | "${JQ}" . >/dev/null 2>&1 || error 1 "method $1 did not return valid JSON output"
    error="$(echo "${json}" | "${JQ}" -e .error 2>/dev/null)" && error 1 "method $1: ${error}"
    echo "${json}"
}

[ -n "${JQ}" ] || error 2 "Dependency not found: jq"

[ $# -ge 1 ] || error 2 "No domain specified"
domain="$1" ; shift

# Start test
output="$(zmb start_domain_test --domain "${domain}")" || exit $?
testid="$(echo "${output}" | "${JQ}" -r .result)" || exit $?

# Wait for test to finish
while true
do
    output="$(zmb test_progress --testid "${testid}")" || exit $?
    progress="$(echo "${output}" | "${JQ}" -r .result)" || exit $?
    printf "\r${progress}%% done" >&2
    if [ "${progress}" -eq 100 ] ; then
        echo >&2
        break
    fi
    sleep 1
done

# Get test results
zmb get_test_results --testid "${testid}" --lang en
echo "testid: ${testid}" >&2
